export const Lato_Black = 'Lato-Black'
export const Lato_Bold = 'Lato-Bold'
export const Lato_Light = 'Lato-Light'
export const Lato_Regular = 'Lato-Regular'
export const Lato_Thin = 'Lato-Thin'

export const Roboto_Light = 'Roboto-Light'
export const Roboto_Medium = 'Roboto-Medium'
export const Roboto_Regular = 'Roboto-Regular'
export const Roboto_Thin = 'Roboto-Thin'